import { useState } from 'react'
import api from '../api/axiosClient'
import Modal from './Modal'
import { money, errorText } from '../utils/warehouse'
import '../pages/Inventory.css'
export default function TableTransferModal({ bill, tables, onClose, onDone }) {
  const [kind, setKind] = useState('Move'), [targetId, setTargetId] = useState(''), [amounts, setAmounts] = useState({}), [guests, setGuests] = useState(''), [note, setNote] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [requestKey] = useState(() => crypto.randomUUID())
  const target = tables.find(t => t.id === Number(targetId))
  const items = bill.items.map(i => ({ idBillInfo: i.idBillInfo, count: kind === 'Split' ? Number(amounts[i.idBillInfo] || 0) : i.count, expectedCount: i.count, expectedSentCount: i.sentCount })).filter(i => i.count > 0)
  const total = items.reduce((s, i) => s + bill.items.find(b => b.idBillInfo === i.idBillInfo).price * i.count, 0)
  const save = async () => { setBusy(true); setError(''); try { const result = await api.post('/TableFood/transfer', { kind, sourceBillId: bill.idBill, targetTableId: target.id, expectedTargetBillId: target.activeBillId || 0, requestKey, note, guestCountToMove: kind === 'Split' && guests !== '' ? Number(guests) : null, items }); await onDone(target.id, result.data.idBill) } catch (e) { setError(errorText(e)) } finally { setBusy(false) } }
  return <Modal title="Chuyển / gộp / tách bàn" width={800} onClose={() => { if (!busy) onClose() }} footer={<><button disabled={busy} onClick={onClose}>Đóng</button><button className="btn btn-primary" disabled={busy || !target || !items.length} onClick={save}>{busy ? 'Đang xử lý...' : 'Xác nhận'}</button></>}><div className="wh-form">{error && <div className="wh-alert">{error}</div>}<fieldset disabled={busy}><div className="wh-fields"><label>Thao tác<select value={kind} onChange={e => { setKind(e.target.value); setTargetId('') }}><option value="Move">Chuyển toàn bộ đơn</option><option value="Merge">Gộp vào bàn đang phục vụ</option><option value="Split">Tách món sang bàn khác</option></select></label><label>Bàn đích<select value={targetId} onChange={e => setTargetId(e.target.value)}><option value="">Chọn bàn đích</option>{tables.filter(t => t.id !== bill.idTable && t.isActive && t.areaActive !== false && (kind !== 'Merge' || t.activeBillId)).map(t => <option key={t.id} value={t.id}>{t.name} · {t.status}</option>)}</select></label></div><p>Từ <b>{bill.tableName}</b> → <b>{target?.name || 'Chưa chọn'}</b>{target?.activeBillId > 0 && ' • Món được cộng vào đơn hiện tại.'}</p>
    <div className="mc-table-wrap"><table className="mc-table"><thead><tr><th>Món / tùy chọn</th><th>Đang phục vụ</th><th>Chuyển</th><th>Đơn giá</th></tr></thead><tbody>{bill.items.map(i => <tr key={i.idBillInfo}><td><b>{i.foodName}</b><small>{i.optionLabel || '—'}</small></td><td>{i.count}<small>Đã báo bếp: {i.sentCount}</small></td><td>{kind === 'Split' ? <input aria-label={`Số lượng chuyển dòng ${i.idBillInfo}`} type="number" min="0" max={i.count} step="1" value={amounts[i.idBillInfo] || 0} onChange={e => setAmounts(v => ({ ...v, [i.idBillInfo]: Number(e.target.value) }))}/> : i.count}</td><td>{money(i.price)}</td></tr>)}</tbody></table></div>
    {kind === 'Split' && <label>Số khách chuyển (tùy chọn, tổng nguồn: {bill.guestCount ?? 'chưa ghi nhận'})<input type="number" min="1" max={(bill.guestCount || 1) - 1} value={guests} placeholder="Chưa xác định" onChange={e => setGuests(e.target.value)}/><small>Để trống: hai đơn chưa xác định số khách, nhập lại trước thanh toán.</small></label>}<label>Ghi chú<textarea maxLength={500} value={note} onChange={e => setNote(e.target.value)}/></label><div className="wh-summary">Giá trị món chuyển: <b>{money(total)}</b><p>Giữ giá, size, topping và trạng thái chế biến. Không trừ kho hay ghi thu lần nữa.</p></div><p className="wh-help">Ưu tiên tách phần chưa báo bếp; phần đã báo chuyển cùng phiếu bếp. Kiểm tra lại giảm giá chưa lưu trên màn hình bán hàng sau thao tác.</p></fieldset></div></Modal>
}
