using CafeManagement.API.Controllers;
using CafeManagement.API.Data;
using CafeManagement.API.DTOs;
using CafeManagement.API.Entities;
using CafeManagement.API.Services;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
int checks = 0;
void Check(bool ok, string name) { if (!ok) throw new Exception("FAIL: " + name); checks++; Console.WriteLine("PASS: " + name); }
JsonElement Json(IActionResult result) => JsonSerializer.SerializeToElement(((OkObjectResult)result).Value);
var cs = new SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("CAFE_DATABASE") ?? await DevelopmentLocalDb.ResolveAsync(@"Server=(localdb)\MSSQLLocalDB;Trusted_Connection=True;TrustServerCertificate=True;")) { InitialCatalog = "CafeCustomerChecks_" + Guid.NewGuid().ToString("N") };
await using var db = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(cs.ConnectionString).Options);
void Clear() => db.ChangeTracker.Clear();
try {
 await db.Database.MigrateAsync();
 Check(!db.Database.HasPendingModelChanges(), "Migrations match runtime model");
 var controller = new CustomerController(db); var checkout = new BillController(db); var invoices = new InvoiceFlow(db); var order = new OrderFlow(db);
 Check(await db.CustomerGroups.CountAsync() == 2, "Default groups seeded");
 var group = await db.CustomerGroups.SingleAsync(g => g.Name == "VIP");
 Check(CustomerCatalog.Phone("+84 901-234-567") == "0901234567", "Phone normalization keeps leading zero");
 var created = Json(await controller.Create(new() { Name = "  Lan demo  ", Phone = "+84 901 234 567", Email = "lan@example.com", Gender = "Nữ", Birthday = new DateTime(2000,1,15), IdGroup = group.Id }));
 var id = created.GetProperty("Id").GetInt32(); Clear();
 Check(created.GetProperty("Name").GetString() == "Lan demo" && created.GetProperty("Phone").GetString() == "0901234567" && created.GetProperty("Code").GetString() == $"KH{id:D6}", "Customer trim normalize and automatic code");
 Check(await controller.Create(new() { Name = "Other", Phone = "0901234567" }) is BadRequestObjectResult, "Duplicate normalized phone rejected"); Clear();
 Check(await controller.Create(new() { Name = "Other", Phone = "abc" }) is BadRequestObjectResult, "Invalid phone rejected"); Clear();
 Check(await controller.Create(new() { Name = "Other", Phone = "0909999999", Email = "bad" }) is BadRequestObjectResult, "Invalid email rejected"); Clear();
 Check(await controller.Create(new() { Name = "Other", Phone = "0909999999", Birthday = DateTime.Today.AddDays(1) }) is BadRequestObjectResult, "Future birthday rejected"); Clear();
 Check(await controller.Create(new() { Name = "Other", Phone = "0909999999", IdGroup = 9999 }) is BadRequestObjectResult, "Unknown group rejected"); Clear();
 Check(await controller.DeleteGroup(group.Id) is BadRequestObjectResult, "Used customer group cannot be deleted");
 Check(await controller.CreateGroup(new() { Name = " VIP " }) is BadRequestObjectResult, "Duplicate group rejected");
 var empty = Json(await controller.CreateGroup(new() { Name = "Empty" })).GetProperty("Id").GetInt32();
 Check(await controller.UpdateGroup(empty, new() { Name = "Renamed" }) is OkResult && await controller.DeleteGroup(empty) is OkResult, "Empty groups can be renamed and deleted"); Clear();
 var preview = Json(await controller.Import(new() { Items = [new() { Name = "A", Phone = "0900000001" }, new() { Name = "B", Phone = "+84900000001" }], Preview = true }));
 Check(!preview.GetProperty("valid").GetBoolean() && preview.GetProperty("errors")[0].GetProperty("row").GetInt32() == 3 && await db.Customers.CountAsync() == 1, "Import preview reports duplicate row without writing"); Clear();
 var invalid = Json(await controller.Import(new() { Items = [new() { Name = "A", Phone = "0900000001" }, new() { Name = "", Phone = "0900000002" }], Preview = false }));
 Check(!invalid.GetProperty("valid").GetBoolean() && await db.Customers.CountAsync() == 1, "Import with errors writes no partial customers"); Clear();
 var imported = Json(await controller.Import(new() { Items = Enumerable.Range(1,20).Select(i => new CreateCustomerDto { Name = "Imported " + i, Phone = "091" + i.ToString("D7") }).ToList(), Preview = false })); Clear();
 Check(imported.GetProperty("valid").GetBoolean() && await db.Customers.CountAsync() == 21, "Valid import adds all rows");
 var list = Json(await controller.List(page:2));
 Check(list.GetProperty("total").GetInt32() == 21 && list.GetProperty("rows").GetArrayLength() == 6, "Management lists beyond ten with stable pagination");
 Check(Json(await controller.List(group:group.Id, gender:"Nữ", birthdayMonth:1)).GetProperty("total").GetInt32() == 1, "Group gender birthday filters");
 Check(Json(await controller.List(search:"+84901234567")).GetProperty("total").GetInt32() == 1, "Search normalizes phone");
 Check(Json(await controller.List(minSpend:0)).GetProperty("total").GetInt32() == 21, "Zero spend includes customers without bills");
 Check(await controller.List(from:DateTime.Today, to:DateTime.Today) is BadRequestObjectResult, "Invalid creation range rejected");
 Check(Json(await controller.Search()).GetArrayLength() == 10, "POS search limited separately from management");
 await controller.Status(id, new() { IsActive = false }); Clear();
 Check(Json(await controller.Search("Lan")).GetArrayLength() == 0 && Json(await controller.List(active:false)).GetProperty("total").GetInt32() == 1, "Inactive customers kept but absent in POS");
 var category = new FoodCategory { Name = "Coffee" }; var food = new Food { Name = "Coffee", Category = category, Price = 20000 }; db.Add(food); await db.SaveChangesAsync();
 async Task<int> NewBill() { var b = await invoices.Takeaway(new() { RequestKey = Guid.NewGuid().ToString() }, "test"); await order.Add(new() { IdBill = b, IdFood = food.Id, Count = 1 }); await order.Send(b); Clear(); return b; }
 var first = await NewBill();
 Check(await checkout.Checkout(first, new() { IdCustomer = id }) is BadRequestObjectResult, "Inactive customer checkout rejected"); Clear();
 await controller.Status(id, new() { IsActive = true }); Clear();
 Check(await checkout.SetCustomer(first, new() { IdCustomer = id }) is OkResult && (await db.Bills.FindAsync(first))!.IdCustomer == id, "Customer selection saved on serving bill"); Clear();
 Check(await checkout.Checkout(first, new() { IdCustomer = id, RedeemPoints = 1 }) is BadRequestObjectResult, "Cannot spend points from current purchase"); Clear();
 Check(await checkout.Checkout(first, new() { IdCustomer = id }) is OkObjectResult, "Checkout associates active customer"); Clear();
 Check((await db.Customers.FindAsync(id))!.Points == 2 && (await db.Bills.FindAsync(first))!.PointsEarned == 2, "Real paid amount earns floor points");
 Check(await checkout.Checkout(first, new() { IdCustomer = id }) is NotFoundObjectResult && await db.CustomerPointEntries.CountAsync() == 1, "Repeated checkout cannot credit points twice"); Clear();
 var second = await NewBill();
 Check(await checkout.Checkout(second, new() { RedeemPoints = 1 }) is BadRequestObjectResult, "Guest cannot redeem points"); Clear();
 Check(await checkout.Checkout(second, new() { IdCustomer = id, RedeemPoints = -1 }) is BadRequestObjectResult, "Negative redemption rejected"); Clear();
 Check(await checkout.Checkout(second, new() { IdCustomer = id, RedeemPoints = 3 }) is BadRequestObjectResult, "Overspending points rejected"); Clear();
 await checkout.Checkout(second, new() { IdCustomer = id, RedeemPoints = 2 }); Clear();
 Check((await db.Bills.FindAsync(second))!.TotalPrice == 19800 && (await db.Customers.FindAsync(id))!.Points == 1, "Point discount applies before earning new points");
 Check(await db.CashEntries.Where(c => c.IdBill == second).SumAsync(c => c.Amount) == 19800, "Cashbook receives only actual payment");
 Check(Json(await controller.Detail(id)).GetProperty("netSpend").GetDecimal() == 39800, "Customer spend matches discounted real receipts");
 await controller.Update(id, new() { Name = "Lan renamed", Phone = "0901234567" }); Clear();
 Check(Json(await new OrdersController(db).Detail(first)).GetProperty("CustomerName").GetString() == "Lan demo", "Paid customer snapshot survives renaming");
 await invoices.Refund(first, new() { Reason = "Refund demo" }, "test"); Clear();
 Check((await db.Customers.FindAsync(id))!.Points == -1, "Refund removes already spent earned points with visible negative balance");
 await invoices.Refund(first, new() { Reason = "Retry" }, "test"); Clear();
 Check(await db.CustomerPointEntries.CountAsync(e => e.IdBill == first && e.Kind == "Refund") == 1 && (await db.Customers.FindAsync(id))!.Points == -1, "Refund retry cannot remove points twice");
 await invoices.Refund(second, new() { Reason = "Refund second" }, "test"); Clear();
 Check((await db.Customers.FindAsync(id))!.Points == 0, "Refund restores redeemed points and removes awarded points exactly");
 var details = Json(await controller.Detail(id));
 Check(details.GetProperty("netSpend").GetDecimal() == 0 && details.GetProperty("refundAmount").GetDecimal() == 39800 && details.GetProperty("visits").GetInt32() == 0 && details.GetProperty("points").GetArrayLength() == 5, "Customer history retains refunds and point ledger");
 var c = (await db.Customers.FindAsync(id))!; c.Points = 200; await db.SaveChangesAsync(); Clear();
 var free = await NewBill(); await checkout.Checkout(free, new() { IdCustomer = id, RedeemPoints = 200 }); Clear();
 var paid = (await db.Bills.Include(b => b.BillInfos).ThenInclude(i => i.Food).SingleAsync(b => b.Id == free));
 Check(paid.HasRecordedPayment && paid.TotalPrice == 0 && !DashboardCalculator.IsEstimated(paid) && DashboardCalculator.NetRevenue(paid) == 0, "Full point redemption is recorded zero payment not invented estimated revenue");
 Check(Json(await new OrdersController(db).List(status:1)).GetProperty("revenue").GetDecimal() == 0, "Order summary excludes point discounts and handles zero receipt");
 Check(!Json(await new OrdersController(db).Detail(free)).GetProperty("Estimated").GetBoolean(), "Full point payment remains refundable");
 Check(Json(await new CashbookController(db).Get(DateTime.Today,DateTime.Today)).GetProperty("Rows").EnumerateArray().All(e => e.GetProperty("Reference").GetString() != $"HD{free:D6}"), "Zero point receipt does not invent a legacy cashbook row");
 var report = Json(await new ReportController(db).GetRevenueReport(DateTime.Today,DateTime.Today.AddDays(1)));
 Check(report[0].GetProperty("TotalRevenue").GetDecimal() == 0, "Revenue report uses actual payment after point redemption");
 await invoices.Refund(free,new() { Reason = "Restore points" },"test"); Clear();
 Check((await db.Customers.FindAsync(id))!.Points == 200 && await db.CashEntries.CountAsync(e => e.IdBill == free) == 0, "Zero cash refund returns points without false cash entries");
 Check(Json(await controller.Detail(id,pointPage:2)).GetProperty("points").GetArrayLength() == 0, "Point ledger pagination bounded");
 var concurrentCustomer = new Customer { Name = "Concurrency demo", Phone = "0999999988", Points = 50 }; var cheap = new Food { Name = "Small coffee", IdCategory = category.Id, Price = 5000 };
 db.AddRange(concurrentCustomer,cheap); await db.SaveChangesAsync();
 var one = new Bill { OrderType = "Takeaway", BillInfos = [new() { Food = cheap, Count = 1, SentCount = 1, UnitPrice = 5000 }] };
 var two = new Bill { OrderType = "Takeaway", BillInfos = [new() { Food = cheap, Count = 1, SentCount = 1, UnitPrice = 5000 }] };
 db.AddRange(one,two); await db.SaveChangesAsync(); Clear();
 async Task<IActionResult> Pay(int billId) { await using var other = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(cs.ConnectionString).Options); return await new BillController(other).Checkout(billId,new() { IdCustomer = concurrentCustomer.Id, RedeemPoints = 50 }); }
 var simultaneous = await Task.WhenAll(Pay(one.Id),Pay(two.Id)); Clear();
 Check(simultaneous.Count(r => r is OkObjectResult) == 1 && simultaneous.Count(r => r is BadRequestObjectResult) == 1, "Concurrent orders cannot both spend the same point balance");
 Check((await db.Customers.FindAsync(concurrentCustomer.Id))!.Points == 0 && await db.CustomerPointEntries.CountAsync(e => e.IdCustomer == concurrentCustomer.Id && e.Kind == "Redeem") == 1, "Concurrent redemption records exactly one deduction");
 Console.WriteLine($"All {checks} customer checks passed.");
} finally { await db.Database.EnsureDeletedAsync(); }
