import { useEffect, useMemo, useState } from 'react'
import { ShieldCheck, Users, Search, Plus, Copy, Save, RefreshCw, LockKeyhole, Check, History } from 'lucide-react'
import api from '../api/axiosClient'
import { errMsg } from '../api/errMsg'
import './Permissions.css'
const label = role => ({ Admin: 'Quản trị viên', Cashier: 'Thu ngân', Kitchen: 'Bếp / Bar' }[role] || role)
const normal = value => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[đĐ]/g, 'd').toLowerCase()
const normalize = (codes, catalog) => { const set = new Set(codes); let changed; do { changed = false; catalog.forEach(r => { if (r.requires && set.has(r.code) && !set.has(r.requires)) changed = set.delete(r.code) || changed }) } while (changed); return [...set] }
export default function Permissions() {
  const [data, setData] = useState({ catalog: [], roles: [], accounts: [] }), [mode, setMode] = useState('roles'), [target, setTarget] = useState(null), [draft, setDraft] = useState(null)
  const [query, setQuery] = useState(''), [filter, setFilter] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(''), [dirty, setDirty] = useState(false), [pending, setPending] = useState(null), [audit, setAudit] = useState(null)
  const select = (item, type = mode) => { setMode(type); setTarget(item); setDirty(false); setPending(null); setError(''); setFilter(''); setDraft(type === 'roles' ? { name: item.name, description: item.description || '', permissions: [...item.permissions], revision: item.revision } : { idRole: item.idRole, overrides: item.overrides.map(x => ({...x})), revision: item.revision }) }
  const move = (item, type = mode) => dirty ? setPending({ item, type }) : select(item, type)
  const load = async (keep = false) => { setLoading(true); try { const { data: next } = await api.get('/Access'); setData(next); setError(''); if (!keep) { const item = mode === 'roles' ? next.roles.find(r => r.id === target?.id) || next.roles[0] : next.accounts.find(a => a.userName === target?.userName) || next.accounts[0]; if (item) select(item) } } catch(e) { setError(errMsg(e, 'Không tải được phân quyền.')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const role = mode === 'roles' ? target : data.roles.find(r => r.id === Number(draft?.idRole))
  const isAdmin = role?.name === 'Admin'
  const base = mode === 'roles' ? draft?.permissions || [] : role?.permissions || []
  const raw = new Set(base); if (mode === 'accounts') (draft?.overrides || []).forEach(p => p.allowed ? raw.add(p.code) : raw.delete(p.code))
  const effective = new Set(isAdmin ? data.catalog.map(r => r.code) : normalize([...raw], data.catalog))
  const groups = useMemo(() => [...new Set(data.catalog.map(p => p.group))], [data.catalog])
  const update = changes => { setDraft(d => ({...d, ...changes})); setDirty(true); setNotice('') }
  const withDependencies = (codes, code) => { const next = new Set(codes); const add = c => { next.add(c); const rule = data.catalog.find(r => r.code === c); if (rule?.requires) add(rule.requires) }; add(code); return [...next] }
  const toggle = (code, value) => update({ permissions: value ? withDependencies(draft.permissions, code) : normalize(draft.permissions.filter(c => c !== code), data.catalog) })
  const override = (code, value) => { let changes = draft.overrides.filter(p => p.code !== code); if (value !== 'inherit') changes.push({ code, allowed: value === 'allow' }); if (value === 'allow') withDependencies([], code).filter(c => c !== code).forEach(c => { if (!base.includes(c) || changes.some(p => p.code === c && !p.allowed)) { changes = changes.filter(p => p.code !== c); changes.push({code:c,allowed:true}) } }); update({overrides:changes}) }
  const create = clone => { const item = { id: null, name: '', description: '', permissions: clone && !isAdmin ? [...effective] : [], revision: '', isAdmin:false }; if (dirty) setPending({item,type:'roles'}); else { select(item, 'roles'); setDirty(true) } }
  const save = async () => { if (busy) return; setBusy(true); setError(''); try { const url = mode === 'roles' ? `/Access/roles${target.id ? '/' + target.id : ''}` : `/Access/accounts/${encodeURIComponent(target.userName)}`; const body = mode === 'accounts' && isAdmin ? {...draft,overrides:[]} : draft; const result = await api[target.id || mode === 'accounts' ? 'put' : 'post'](url, body); const latest = await api.get('/Access'); setData(latest.data); select(result.data); setNotice('Đã lưu. API áp dụng ngay; màn hình nhân viên tự cập nhật trong vài giây.'); window.dispatchEvent(new Event('access-refresh')); if (audit) setAudit((await api.get('/Access/audit')).data) } catch(e) { setError(errMsg(e, 'Không lưu được phân quyền.')) } finally { setBusy(false) } }
  const entries = (mode === 'roles' ? data.roles : data.accounts).filter(x => normal(mode === 'roles' ? `${label(x.name)} ${x.description || ''}` : `${x.displayName} ${x.userName}`).includes(normal(query)))
  return <main className="access-page">
    <header className="access-heading"><div><span>QUẢN TRỊ HỆ THỐNG</span><h1><ShieldCheck/> Phân quyền</h1><p>Cấp đúng quyền cho từng nhóm và từng nhân viên.</p></div><div><button disabled={busy || loading || dirty} onClick={() => load()}><RefreshCw size={17}/> Tải lại</button><button onClick={async () => { try { setAudit(audit ? null : (await api.get('/Access/audit')).data) } catch(e) { setError(errMsg(e)) } }}><History size={17}/> Lịch sử</button><button className="access-primary" disabled={busy || loading} onClick={() => create(false)}><Plus size={17}/> Thêm nhóm</button></div></header>
    <div className="access-banner"><LockKeyhole size={22}/><div><b>Admin luôn có toàn bộ {data.catalog.length} quyền</b><p>Chỉ Admin được sửa phân quyền. Không thể tự hạ quyền hoặc làm mất quản trị viên cuối cùng.</p></div></div>
    {error && <p className="access-error" role="alert">{error}</p>}{notice && <p className="access-notice" role="status"><Check size={18}/>{notice}</p>}
    {pending && <div className="access-unsaved"><b>Có thay đổi chưa lưu.</b><span>Lưu trước, hoặc bỏ thay đổi để chuyển mục.</span><button onClick={() => select(pending.item, pending.type)}>Bỏ thay đổi và chuyển</button><button onClick={() => setPending(null)}>Tiếp tục sửa</button></div>}
    <div className="access-layout"><aside className="access-sidebar"><div className="access-tabs"><button disabled={busy} className={mode === 'roles' ? 'selected' : ''} onClick={() => { if (data.roles[0]) move(data.roles[0], 'roles') }}><ShieldCheck size={16}/> Nhóm quyền</button><button disabled={busy} className={mode === 'accounts' ? 'selected' : ''} onClick={() => { if (data.accounts[0]) move(data.accounts[0], 'accounts') }}><Users size={16}/> Nhân viên</button></div><label className="access-search"><Search size={17}/><input aria-label="Tìm nhóm hoặc nhân viên" placeholder="Tìm nhóm / nhân viên..." value={query} onChange={e => setQuery(e.target.value)}/></label><div className="access-targets">{entries.map(x => <button key={x.id || x.userName} disabled={busy} className={(mode === 'roles' ? target?.id === x.id : target?.userName === x.userName) ? 'selected' : ''} onClick={() => move(x)}><span className="access-avatar">{mode === 'roles' ? <ShieldCheck size={19}/> : x.displayName.slice(0,1)}</span><span><b>{mode === 'roles' ? label(x.name) : x.displayName}</b><small>{mode === 'roles' ? `${x.accountCount} tài khoản · ${x.isAdmin ? 'Toàn quyền' : x.permissions.length + ' quyền'}` : `${x.userName} · ${label(x.roleName)}${x.isActive ? '' : ' · Đã khóa'}`}</small></span>{x.isAdmin && <LockKeyhole size={15}/>}</button>)}{!entries.length && <p>Không có kết quả.</p>}</div></aside>
    <section className="access-editor">{loading ? <p>Đang tải phân quyền...</p> : draft && <><div className="access-editor-title"><div><h2>{mode === 'roles' ? target.id ? label(target.name) : 'Nhóm quyền mới' : target.displayName}</h2><p>{mode === 'roles' ? 'Nhân viên trong nhóm kế thừa các quyền được chọn.' : `${target.userName} · Theo nhóm, cho phép riêng hoặc không cho phép.`}</p></div><span className="access-counter">{effective.size} / {data.catalog.length} quyền</span></div>
      <div className="access-meta">{mode === 'roles' ? <><label>Tên nhóm<input aria-label="Tên nhóm quyền" disabled={isAdmin || busy} maxLength={50} value={draft.name} onChange={e => update({name:e.target.value})}/></label><label>Mô tả<input disabled={isAdmin || busy} maxLength={255} value={draft.description} onChange={e => update({description:e.target.value})}/></label></> : <><label>Nhóm quyền<select aria-label="Nhóm quyền nhân viên" disabled={busy} value={draft.idRole} onChange={e => update({idRole:Number(e.target.value),overrides:[]})}>{data.roles.map(r => <option key={r.id} value={r.id}>{label(r.name)}</option>)}</select></label><button disabled={busy || isAdmin || !draft.overrides.length} onClick={() => update({overrides:[]})}>Xóa quyền riêng · theo nhóm</button></>}</div>
      {isAdmin ? <div className="access-admin"><ShieldCheck/><b>Toàn quyền quản trị</b><p>Quyền Admin được hệ thống bảo vệ, không cần tích chọn.</p></div> : <><div className="access-matrix-tools"><label className="access-search"><Search size={17}/><input placeholder="Tìm chức năng cần cấp quyền..." aria-label="Tìm quyền" value={filter} onChange={e => setFilter(e.target.value)}/></label>{mode === 'roles' && <button disabled={busy} onClick={() => create(true)}><Copy size={16}/> Sao chép nhóm</button>}</div>
        {groups.map(group => { const rules = data.catalog.filter(p => p.group === group && normal(`${p.group} ${p.name}`).includes(normal(filter))); if (!rules.length) return null; return <article className="access-group" key={group}><div className="access-group-title"><h3>{group}</h3><span>{data.catalog.filter(p => p.group === group && effective.has(p.code)).length} quyền đang có</span>{mode === 'roles' && <button disabled={busy} onClick={() => { let codes = [...draft.permissions]; const all = data.catalog.filter(p => p.group === group); const selected = all.every(p => effective.has(p.code)); all.forEach(p => { codes = selected ? codes.filter(c => c !== p.code) : withDependencies(codes,p.code) }); update({permissions:normalize(codes,data.catalog)}) }}>{data.catalog.filter(p => p.group === group).every(p => effective.has(p.code)) ? 'Bỏ cả nhóm' : 'Chọn cả nhóm'}</button>}</div>{rules.map(rule => { const value = draft.overrides?.find(p => p.code === rule.code); return <div className="access-rule" key={rule.code}><label>{mode === 'roles' && <input type="checkbox" checked={effective.has(rule.code)} disabled={busy} onChange={e => toggle(rule.code,e.target.checked)}/>}<span>{rule.name}{rule.requires && <small>Cần: {data.catalog.find(p => p.code === rule.requires)?.name}</small>}</span></label>{mode === 'accounts' && <select aria-label={rule.name} disabled={busy} value={value == null ? 'inherit' : value.allowed ? 'allow' : 'deny'} onChange={e => override(rule.code,e.target.value)}><option value="inherit">Theo nhóm ({base.includes(rule.code) ? 'có' : 'không'})</option><option value="allow">Cho phép riêng</option><option value="deny">Không cho phép</option></select>}<span className={`access-state ${effective.has(rule.code) ? 'yes' : ''}`}>{effective.has(rule.code) ? 'Được phép' : 'Không được'}</span></div> })}</article> })}
        {!data.catalog.some(p => normal(`${p.group} ${p.name}`).includes(normal(filter))) && <p>Không có quyền phù hợp.</p>}
      </>}
      <footer className="access-save"><span>{dirty ? 'Có thay đổi chưa lưu' : 'Đã đồng bộ với hệ thống'}<small>Quyền riêng ưu tiên hơn nhóm. Quyền thao tác cần quyền xem tương ứng.</small></span><button className="access-primary" disabled={busy || !dirty || mode === 'roles' && isAdmin || mode === 'roles' && !draft.name.trim()} onClick={save}><Save size={17}/>{busy ? 'Đang lưu...' : 'Lưu phân quyền'}</button></footer>
    </>}</section></div>
    {audit && <section className="access-history"><h2>Lịch sử phân quyền gần đây</h2>{audit.map(row => <p key={row.id}><b>{row.actor}</b><span>Cập nhật {row.target}</span><time>{new Date(row.createdAt + 'Z').toLocaleString('vi-VN')}</time></p>)}{!audit.length && <p>Chưa có thay đổi.</p>}</section>}
  </main>
}
