using CafeManagement.API.Data;
using CafeManagement.API.Entities;
using CafeManagement.API.DTOs;
using CafeManagement.API.Controllers;
using CafeManagement.API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Data.SqlClient;
using System.Security.Claims;
using System.Text.Json;
int checks = 0;
void Check(bool ok, string name) { if (!ok) throw new Exception("FAIL: " + name); checks++; Console.WriteLine("PASS: " + name); }
async Task Reject(Func<Task> action, string name) { try { await action(); } catch (InvalidOperationException) { Check(true, name); return; } throw new Exception("FAIL: " + name); }
var connection = new SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("CAFE_DATABASE") ?? @"Server=(localdb)\MSSQLLocalDB;Trusted_Connection=True;TrustServerCertificate=True;") { InitialCatalog = "CafeWarehouseChecks_" + Guid.NewGuid().ToString("N") };
await using var db = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(connection.ConnectionString).Options);
try {
  await db.Database.MigrateAsync();
  var role = new Role { Name = "Test" }; var supplier = new Supplier { Name = "Supplier" };
  db.AddRange(role, supplier); await db.SaveChangesAsync(); db.Accounts.Add(new Account { UserName = "tester", PassWord = "test", IdRole = role.Id }); await db.SaveChangesAsync();
  var catalog = new WarehouseCatalog(db);
  var ingredient = await catalog.Save(new() { Name = "Coffee", Unit = "g", Quantity = 0, UnitCost = 200, Units = [new() { Name = "kg", Factor = 1000 }] }, null, "tester");
  var unit = await db.IngredientUnits.SingleAsync();
  var flow = new WarehouseFlow(db);
  var input = new WarehouseImportWrite { IdSupplier = supplier.Id, PaidAmount = 150000, RequestKey = Guid.NewGuid().ToString(), Items = [new() { IdIngredient = ingredient.Id, IdUnit = unit.Id, Quantity = 2, Price = 200000, LotCode = "FIRST", ExpiryDate = DateTime.Today.AddDays(2) }] };
  var receiptId = await flow.Import(input, "tester"); db.ChangeTracker.Clear();
  Check((await db.Ingredients.FindAsync(ingredient.Id))!.Quantity == 2000, "Two kg become 2000 g");
  var receipt = (await db.ImportReceipts.FindAsync(receiptId))!;
  Check(receipt.TotalAmount == 400000 && receipt.HasPaymentTracking, "Receipt tracks full purchase separately from payment");
  Check(await db.CashEntries.SumAsync(c => c.Amount) == 150000, "Only paid amount enters cashbook");
  Check(await flow.Import(input, "tester") == receiptId && await db.ImportReceipts.CountAsync() == 1, "Import retry creates no duplicate stock or expense"); db.ChangeTracker.Clear();
  var payment = new SupplierPaymentWrite { Amount = 50000, RequestKey = Guid.NewGuid().ToString(), PaymentMethod = "Transfer" };
  var paymentId = await flow.Pay(receiptId, payment, "tester");
  Check(await flow.Pay(receiptId, payment, "tester") == paymentId && await db.CashEntries.SumAsync(c => c.Amount) == 200000, "Payment retry is idempotent"); db.ChangeTracker.Clear();
  await Reject(async () => await flow.Pay(receiptId, new() { Amount = 200001 }, "tester"), "Overpayment rejected"); db.ChangeTracker.Clear();
  Check(await db.CashEntries.SumAsync(c => c.Amount) == 200000, "Rejected overpayment leaves cashbook unchanged");
  var second = await flow.Import(new() { IdSupplier = supplier.Id, Items = [new() { IdIngredient = ingredient.Id, Quantity = 1000, Price = 300, LotCode = "SECOND", ExpiryDate = DateTime.Today.AddDays(10) }] }, "tester"); db.ChangeTracker.Clear();
  Check((await db.Ingredients.FindAsync(ingredient.Id))!.UnitCost == 233.3333m, "Weighted average cost on remaining lots");
  var export = new WarehouseOperationWrite { Kind = "Export", Note = "Test export", RequestKey = Guid.NewGuid().ToString(), Items = [new() { IdIngredient = ingredient.Id, Quantity = 2100 }] };
  var exportId = await flow.Operate(export, "tester"); db.ChangeTracker.Clear();
  Check((await db.StockLots.SingleAsync(l => l.Code == "FIRST")).Quantity == 0 && (await db.StockLots.SingleAsync(l => l.Code == "SECOND")).Quantity == 900, "FEFO spans lots in expiration order");
  Check(await flow.Operate(export, "tester") == exportId && (await db.Ingredients.FindAsync(ingredient.Id))!.Quantity == 900, "Export retry does not deduct twice"); db.ChangeTracker.Clear();
  await Reject(async () => await flow.Operate(new() { Kind = "Count", Note = "Stale count", Items = [new() { IdIngredient = ingredient.Id, ExpectedQuantity = 1000, Quantity = 800 }] }, "tester"), "Stale count blocked"); db.ChangeTracker.Clear();
  await flow.Operate(new() { Kind = "Count", Note = "Actual count", Items = [new() { IdIngredient = ingredient.Id, ExpectedQuantity = 900, Quantity = 800 }] }, "tester"); db.ChangeTracker.Clear();
  Check((await db.Ingredients.FindAsync(ingredient.Id))!.Quantity == 800 && await db.StockLots.SumAsync(l => l.Quantity) == 800, "Count reconciles lot and total stock");
  var lot = await db.StockLots.SingleAsync(l => l.Code == "SECOND"); lot.ExpiryDate = DateTime.Today.AddDays(-1); await db.SaveChangesAsync();
  await Reject(async () => await flow.Operate(new() { Kind = "Export", Note = "Expired", Items = [new() { IdIngredient = ingredient.Id, Quantity = 1 }] }, "tester"), "Expired lots blocked for normal export"); db.ChangeTracker.Clear();
  await flow.Operate(new() { Kind = "Disposal", Note = "Expired disposal", Items = [new() { IdIngredient = ingredient.Id, IdLot = lot.Id, Quantity = 50 }] }, "tester"); db.ChangeTracker.Clear();
  Check((await db.Ingredients.FindAsync(ingredient.Id))!.Quantity == 750, "Disposal can remove expired stock");
  var documentCount = await db.WarehouseDocuments.CountAsync();
  await Reject(async () => await flow.Operate(new() { Kind = "Export", Note = "Atomic", Items = [new() { IdIngredient = ingredient.Id, Quantity = 1 }] }, "tester"), "Failed operation rolls back document"); db.ChangeTracker.Clear();
  Check(await db.WarehouseDocuments.CountAsync() == documentCount, "No orphan documents after rollback");
  // Two valid lines: the first writes stock, the second fails. All writes must roll back.
  var other = await catalog.Save(new() { Name = "Sugar", Unit = "g", Quantity = 10, UnitCost = 1 }, null, "tester"); db.ChangeTracker.Clear();
  await Reject(async () => await flow.Operate(new() { Kind = "Export", Note = "Multi-line rollback", Items = [new() { IdIngredient = other.Id, Quantity = 5 }, new() { IdIngredient = ingredient.Id, Quantity = 1 }] }, "tester"), "Later line failure rolls back earlier consumption"); db.ChangeTracker.Clear();
  Check((await db.Ingredients.FindAsync(other.Id))!.Quantity == 10 && await db.WarehouseDocuments.CountAsync() == documentCount, "Atomic stock and document rollback verified");
  var context = new ControllerContext { HttpContext = new DefaultHttpContext { User = new ClaimsPrincipal(new ClaimsIdentity([new Claim(ClaimTypes.NameIdentifier, "tester")], "test")) } };
  var controller = new WarehouseController(db) { ControllerContext = context };
  var supplierResult = (OkObjectResult)await controller.Suppliers(); var json = JsonSerializer.SerializeToElement(supplierResult.Value);
  Check(json[0].GetProperty("Debt").GetDecimal() == 500000, "Supplier debt includes unpaid receipts minus actual payments");
  Check(await controller.Receipts() is OkObjectResult && await controller.Ingredients() is OkObjectResult && await controller.Documents() is OkObjectResult && await controller.Movements(null, null, null) is OkObjectResult, "Warehouse GET queries execute against SQL Server");
  var cash = new CashbookController(db) { ControllerContext = context };
  var cashResult = (OkObjectResult)await cash.Get(DateTime.Today, DateTime.Today); json = JsonSerializer.SerializeToElement(cashResult.Value);
  Check(json.GetProperty("TotalOut").GetDecimal() == 200000, "Cashbook excludes unpaid supplier debt");
  var manual = new CashEntryWrite { Amount = 10000, Direction = "In", Category = "Other", Note = "Test", RequestKey = Guid.NewGuid().ToString() };
  Check(await cash.Create(manual) is OkObjectResult && await cash.Create(manual) is OkObjectResult && await db.CashEntries.CountAsync(c => c.RequestKey == manual.RequestKey) == 1, "Manual cash entry retry creates one record");
  var excelCount = await db.Ingredients.CountAsync(); var excelResult = (OkObjectResult)await controller.Excel(new() { Preview = false, Items = [new() { Name = "Valid excel", Unit = "g" }, new() { Name = "Invalid excel", Unit = "g", Quantity = -1 }] });
  Check(!JsonSerializer.SerializeToElement(excelResult.Value).GetProperty("valid").GetBoolean() && await db.Ingredients.CountAsync() == excelCount, "Invalid Excel batch imports no rows");
  ingredient = (await db.Ingredients.FindAsync(ingredient.Id))!;
  await new StockLots(db).Add(ingredient, 10, 200, "Import", "Early lot", code: "EARLY", expiry: DateTime.Today.AddDays(1));
  await new StockLots(db).Add(ingredient, 20, 200, "Import", "Late lot", code: "LATE", expiry: DateTime.Today.AddDays(5));
  var category = new FoodCategory { Name = "Drinks" }; var table = new TableFood { Name = "Test table", IsActive = true }; db.AddRange(category, table); await db.SaveChangesAsync();
  var food = new Food(); db.Foods.Add(food); await new MenuCatalog(db).Save(food, new CreateFoodDto { Name = "Coffee drink", Price = 10000, IdCategory = category.Id, Recipe = [new() { IdIngredient = ingredient.Id, Amount = 12 }] });
  var orders = new OrderFlow(db); var billId = await orders.Add(new() { IdTable = table.Id, IdFood = food.Id, Count = 2 }); await orders.Send(billId); db.ChangeTracker.Clear();
  Check((await db.StockLots.SingleAsync(l => l.Code == "EARLY")).Quantity == 0 && (await db.StockLots.SingleAsync(l => l.Code == "LATE")).Quantity == 6, "Kitchen uses FEFO and skips expired inventory");
  var line = await db.BillInfos.SingleAsync(i => i.IdBill == billId); await orders.Cancel(line.Id, new() { Count = 1, Reason = "Refund pending" }); db.ChangeTracker.Clear();
  Check((await db.StockLots.SingleAsync(l => l.Code == "EARLY")).Quantity == 5 && (await db.StockLots.SingleAsync(l => l.Code == "LATE")).Quantity == 13, "Partial kitchen refund restores exact source lots");
  var detail = await db.KitchenOrderDetails.SingleAsync(k => k.IdBillInfo == line.Id); detail.Status = "Cooking"; await db.SaveChangesAsync(); var beforeWaste = (await db.Ingredients.FindAsync(ingredient.Id))!.Quantity;
  await orders.Cancel(line.Id, new() { Count = 1, Reason = "Waste cooked" }); db.ChangeTracker.Clear();
  Check((await db.Ingredients.FindAsync(ingredient.Id))!.Quantity == beforeWaste && await db.StockMovements.Where(m => m.Kind == "Waste").SumAsync(m => m.Quantity) == -12, "Cooking cancellation records waste without deducting stock again");
  Check(await db.StockLots.Where(l => l.IdIngredient == ingredient.Id).SumAsync(l => l.Quantity) == (await db.Ingredients.FindAsync(ingredient.Id))!.Quantity, "Kitchen operations preserve total and lot reconciliation");
  Console.WriteLine($"All {checks} warehouse checks passed.");
} finally { await db.Database.EnsureDeletedAsync(); }
