using CafeManagement.API.Data;
using CafeManagement.API.Entities;
using CafeManagement.API.DTOs;
using CafeManagement.API.Controllers;
using CafeManagement.API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
int checks = 0;
void Check(bool ok, string name) { if (!ok) throw new Exception("FAIL: " + name); checks++; Console.WriteLine("PASS: " + name); }
async Task Reject(Func<Task> action, string name) { try { await action(); } catch (InvalidOperationException) { Check(true, name); dbClear(); return; } throw new Exception("FAIL: " + name); }
var cs = new SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("CAFE_DATABASE") ?? @"Server=(localdb)\MSSQLLocalDB;Trusted_Connection=True;TrustServerCertificate=True;") { InitialCatalog = "CafeTableChecks_" + Guid.NewGuid().ToString("N") };
await using var db = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(cs.ConnectionString).Options);
void dbClear() => db.ChangeTracker.Clear();
try {
 await db.Database.MigrateAsync();
 var area = new Area { Name = "Patio" }; var a = new TableFood { Name = "A", Area = area }; var b = new TableFood { Name = "B", Area = area }; var c = new TableFood { Name = "C", Area = area }; var stopped = new TableFood { Name = "Stopped", IsActive = false };
 var category = new FoodCategory { Name = "Drinks" }; var milk = new Ingredient { Name = "Milk", Unit = "ml", Quantity = 1000, UnitCost = 10 };
 db.AddRange(a, b, c, stopped, category, milk); await db.SaveChangesAsync();
 var food = new Food(); db.Foods.Add(food); await new MenuCatalog(db).Save(food, new CreateFoodDto { Name = "Latte", Price = 35000, IdCategory = category.Id, Recipe = [new() { IdIngredient = milk.Id, Amount = 10 }] });
 var orders = new OrderFlow(db); var transfers = new TableFlow(db);
 await Reject(async () => await orders.Add(new() { IdTable = stopped.Id, IdFood = food.Id, Count = 1 }), "Stopped table rejects new order");
 var billId = await orders.Add(new() { IdTable = a.Id, IdFood = food.Id, Count = 5 }); await orders.Send(billId); dbClear();
 var line = await db.BillInfos.SingleAsync(i => i.IdBill == billId); await orders.Cancel(line.Id, new() { Count = 1, Reason = "Before split" }); dbClear();
 Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 960, "Initial kitchen consumption and cancellation");
 var split = new TableTransferWrite { Kind = "Split", SourceBillId = billId, TargetTableId = b.Id, RequestKey = Guid.NewGuid().ToString(), Items = [new() { IdBillInfo = line.Id, Count = 2, ExpectedCount = 4, ExpectedSentCount = 4 }] };
 var targetId = await transfers.Transfer(split, "tester"); dbClear();
 Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 960 && await db.CashEntries.CountAsync() == 0, "Split changes neither stock nor cash");
 Check((await db.BillInfos.FindAsync(line.Id))!.Count == 2 && (await db.BillInfos.SingleAsync(i => i.IdBill == targetId)).Count == 2, "Split partitions quantities");
 Check((await db.BillInfos.SingleAsync(i => i.IdBill == targetId)).UnitPrice == 35000 && (await db.BillInfos.SingleAsync(i => i.IdBill == targetId)).SentCount == 2, "Split preserves price and kitchen sent count");
 Check(await transfers.Transfer(split, "tester") == targetId && await db.TableOperations.CountAsync() == 1, "Split retry is idempotent"); dbClear();
 Check(await orders.Send(targetId) == null, "Split cannot resend existing kitchen quantities");
 var movedLine = await db.BillInfos.SingleAsync(i => i.IdBill == targetId); await orders.Cancel(movedLine.Id, new() { Count = 1, Reason = "After split" }); dbClear();
 Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 970, "Cancel after split returns only selected ingredients");
 await orders.Cancel(line.Id, new() { Count = 1, Reason = "Original side" }); dbClear();
 Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 980 && await db.StockLots.SumAsync(l => l.Quantity) == 980, "Both sides refund exact lot after prior partial cancellation");
 var merge = new TableTransferWrite { Kind = "Merge", SourceBillId = billId, TargetTableId = b.Id, ExpectedTargetBillId = targetId, RequestKey = Guid.NewGuid().ToString(), Items = [new() { IdBillInfo = line.Id, Count = 1, ExpectedCount = 1, ExpectedSentCount = 1 }] };
 Check(await transfers.Transfer(merge, "tester") == targetId, "Merge uses destination active bill"); dbClear();
 Check((await db.Bills.FindAsync(billId))!.Status == 2 && (await db.TableFoods.FindAsync(a.Id))!.Status == "Trống", "Merge closes source without recording revenue");
 Check(await db.BillInfos.Where(i => i.IdBill == targetId).SumAsync(i => i.Count) == 2 && (await db.Ingredients.FindAsync(milk.Id))!.Quantity == 980, "Merge preserves quantities and inventory");
 var destinationLines = await db.BillInfos.Where(i => i.IdBill == targetId && i.Count > 0).ToListAsync();
 var move = new TableTransferWrite { Kind = "Move", SourceBillId = targetId, TargetTableId = c.Id, RequestKey = Guid.NewGuid().ToString(), Items = destinationLines.Select(i => new TableTransferLine { IdBillInfo = i.Id, Count = i.Count, ExpectedCount = i.Count, ExpectedSentCount = i.SentCount }).ToList() };
 Check(await transfers.Transfer(move, "tester") == targetId, "Move to empty table keeps same bill identity"); dbClear();
 Check((await db.Bills.FindAsync(targetId))!.IdTable == c.Id && (await db.TableFoods.FindAsync(b.Id))!.Status == "Trống", "Move updates source and destination states");
 var kitchenJson = JsonSerializer.SerializeToElement(((OkObjectResult)await new KitchenController(db).Pending()).Value);
 Check(kitchenJson.EnumerateArray().All(o => o.GetProperty("TableName").GetString() == "C"), "Kitchen queue shows destination after merge and move");
 var tableController = new TableFoodController(db);
 Check(await tableController.Delete(c.Id) is BadRequestObjectResult, "Occupied table cannot be disabled"); dbClear();
 Check(await tableController.EditArea(area.Id, new() { Name = "Patio", IsActive = false }) is BadRequestObjectResult, "Occupied area cannot be disabled"); dbClear();
 var checkout = new BillController(db); Check(await checkout.Checkout(targetId, new() { PaymentMethod = "Transfer", GuestCount = 2 }) is OkObjectResult, "Transferred bill checks out normally");
 Check((await db.CashEntries.SingleAsync()).Amount == 70000 && await db.CashEntries.CountAsync() == 1, "Only final checkout records income");
 Check(await tableController.Delete(c.Id) is OkObjectResult && await db.Bills.AnyAsync(bi => bi.Id == targetId), "Disabled table preserves paid bill history"); dbClear();
 Check(await new PublicMenuController(db).Get(c.Id) is NotFoundObjectResult, "Public menu rejects inactive table");
 var publicMenu = JsonSerializer.SerializeToElement(((OkObjectResult)await new PublicMenuController(db).Get(a.Id)).Value);
 Check(!publicMenu.ToString().Contains("CostPrice") && !publicMenu.ToString().Contains("IngredientsJson"), "Public menu exposes no cost or recipe data");
 var countBefore = await db.TableFoods.CountAsync(); var excel = (OkObjectResult)await tableController.Excel(new() { Preview = false, Items = [new() { Name = "Valid" }, new() { Name = "Bad", Seats = 0 }] });
 Check(!JsonSerializer.SerializeToElement(excel.Value).GetProperty("valid").GetBoolean() && await db.TableFoods.CountAsync() == countBefore, "Invalid Excel batch creates no partial tables");
 var freshId = await orders.Add(new() { IdTable = a.Id, IdFood = food.Id, Count = 3 }); var fresh = await db.BillInfos.SingleAsync(i => i.IdBill == freshId);
 var stale = new TableTransferWrite { Kind = "Split", SourceBillId = freshId, TargetTableId = b.Id, RequestKey = Guid.NewGuid().ToString(), Items = [new() { IdBillInfo = fresh.Id, Count = 1, ExpectedCount = 2, ExpectedSentCount = 0 }] };
 await Reject(async () => await transfers.Transfer(stale, "tester"), "Stale source quantities blocked atomically");
 Check((await db.BillInfos.FindAsync(fresh.Id))!.Count == 3 && !await db.Bills.AnyAsync(bi => bi.IdTable == b.Id && bi.Status == 0), "Stale transfer creates no destination bill");
 var unreported = new TableTransferWrite { Kind = "Split", SourceBillId = freshId, TargetTableId = b.Id, RequestKey = Guid.NewGuid().ToString(), Items = [new() { IdBillInfo = fresh.Id, Count = 1, ExpectedCount = 3, ExpectedSentCount = 0 }] };
 var newId = await transfers.Transfer(unreported, "tester"); dbClear();
 Check((await db.BillInfos.SingleAsync(i => i.IdBill == newId)).SentCount == 0, "Unreported split stays unreported");
 Check((await new StockReservations(db).Held()).GetValueOrDefault(milk.Id) == 30, "Unreported split preserves combined ingredient reservation");
 await orders.Send(newId); dbClear(); Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 970, "Sending split unreported item deducts exactly once");
 Check((await new StockReservations(db).Held()).GetValueOrDefault(milk.Id) == 20, "Sending split releases only destination reservation");
 var detail = await db.KitchenOrderDetails.SingleAsync(d => d.BillInfo!.IdBill == newId); detail.Status = "Cooking"; await db.SaveChangesAsync(); var newLine = await db.BillInfos.SingleAsync(i => i.IdBill == newId);
 await orders.Cancel(newLine.Id, new() { Count = 1, Reason = "Cooked waste" }); dbClear(); Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 970, "Cooked split cancellation does not refund or deduct twice");
 Console.WriteLine($"All {checks} table checks passed.");
} finally { await db.Database.EnsureDeletedAsync(); }
