using CafeManagement.API.Controllers;
using CafeManagement.API.Data;
using CafeManagement.API.DTOs;
using CafeManagement.API.Entities;
using CafeManagement.API.Services;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
int checks = 0;
void Check(bool ok, string name) { if (!ok) throw new Exception("FAIL: " + name); checks++; Console.WriteLine("PASS: " + name); }
var cs = new SqlConnectionStringBuilder(Environment.GetEnvironmentVariable("CAFE_DATABASE") ?? @"Server=(localdb)\MSSQLLocalDB;Trusted_Connection=True;TrustServerCertificate=True;") { InitialCatalog = "CafeOrdersChecks_" + Guid.NewGuid().ToString("N") };
await using var db = new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseSqlServer(cs.ConnectionString).Options);
void Clear() => db.ChangeTracker.Clear();
async Task Reject(Func<Task> fn, string name) { try { await fn(); } catch (InvalidOperationException) { Check(true, name); Clear(); return; } throw new Exception("FAIL: " + name); }
JsonElement Json(IActionResult result) => JsonSerializer.SerializeToElement(((OkObjectResult)result).Value);
try {
 await db.Database.MigrateAsync();
 var table = new TableFood { Name = "A", IsActive = true };
 var category = new FoodCategory { Name = "Coffee" }; var milk = new Ingredient { Name = "Milk", Unit = "ml", Quantity = 1000, UnitCost = 10 };
 db.AddRange(table, category, milk); await db.SaveChangesAsync();
 var food = new Food(); db.Foods.Add(food); await new MenuCatalog(db).Save(food, new CreateFoodDto { Name = "Latte", Price = 35000, IdCategory = category.Id, Recipe = [new() { IdIngredient = milk.Id, Amount = 10 }] });
 var invoices = new InvoiceFlow(db); var flow = new OrderFlow(db); var controller = new OrdersController(db); var checkout = new BillController(db); var kitchen = new KitchenController(db);
 var create = new TakeawayWrite { RequestKey = Guid.NewGuid().ToString(), Label = "Nam demo", Note = "Less sugar" };
 var id = await invoices.Takeaway(create, "tester"); Clear();
 Check((await db.Bills.FindAsync(id))!.IdTable == null && (await db.Bills.FindAsync(id))!.OrderType == "Takeaway", "Takeaway has no table");
 Check(await invoices.Takeaway(create, "tester") == id && await db.Bills.CountAsync() == 1, "Takeaway retry creates only one order"); Clear();
 await flow.Add(new() { IdBill = id, IdFood = food.Id, Count = 2 }); Clear();
 Check((await db.TableFoods.FindAsync(table.Id))!.Status == "Trống" && (await db.Ingredients.FindAsync(milk.Id))!.Quantity == 1000, "Adding takeaway leaves tables and stock untouched");
 await Reject(async () => await flow.Add(new() { IdBill = id, IdTable = table.Id, IdFood = food.Id, Count = 1 }), "Mismatched table rejected");
 Check(await checkout.Checkout(id, new() { PaymentMethod = "Invalid" }) is BadRequestObjectResult && !await db.KitchenOrders.AnyAsync(), "Invalid payment cannot report kitchen"); Clear();
 await flow.Send(id); Clear();
 Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 980, "Takeaway kitchen report deducts exactly once");
 Check(await flow.Send(id) == null && (await db.Ingredients.FindAsync(milk.Id))!.Quantity == 980, "Repeat kitchen report cannot deduct twice");
 var pending = Json(await kitchen.Pending()); Check(pending[0].GetProperty("TableName").GetString() == "Nam demo" && pending[0].GetProperty("OrderType").GetString() == "Takeaway", "Kitchen shows takeaway label");
 var kitchenId = (await db.KitchenOrders.SingleAsync()).Id;
 Check(await kitchen.Status(kitchenId, new() { Status = "Completed" }) is BadRequestObjectResult, "Kitchen cannot skip cooking"); Clear();
 Check(await kitchen.Status(kitchenId, new() { Status = "Cooking" }) is OkResult, "Kitchen starts cooking"); Clear();
 Check(await kitchen.Status(kitchenId, new() { Status = "Completed" }) is OkResult, "Kitchen completes cooking"); Clear();
 Check(Json(await kitchen.Pending()).GetArrayLength() == 0, "Completed ticket leaves kitchen queue");
 Check(Json(await kitchen.Pending(completed:true)).GetArrayLength() == 1, "Kitchen completed view retains today's finished ticket");
 var finished = await db.KitchenOrders.FindAsync(kitchenId); var reportedAt = finished!.CreatedAt; finished.CreatedAt = DateTime.Today.AddDays(-1); await db.SaveChangesAsync(); Clear();
 Check(Json(await kitchen.Pending(completed:true)).GetArrayLength() == 0, "Completed view excludes tickets reported before today");
 finished = await db.KitchenOrders.FindAsync(kitchenId); finished!.CreatedAt = reportedAt; await db.SaveChangesAsync(); Clear();
 Check(await checkout.Checkout(id, new() { PaymentMethod = "Transfer", Discount = 10 }) is OkObjectResult, "Takeaway checkout succeeds"); Clear();
 Check((await db.Bills.FindAsync(id))!.TotalPrice == 63000 && (await db.CashEntries.SingleAsync()).Amount == 63000, "Discounted payment recorded once");
 Check(await checkout.Checkout(id, new() { PaymentMethod = "Transfer" }) is NotFoundObjectResult && await db.CashEntries.CountAsync() == 1, "Repeat checkout cannot receive twice");
 await Reject(async () => await flow.Add(new() { IdBill = id, IdFood = food.Id, Count = 1 }), "Paid order cannot be edited");
 var savedFood = (await db.Foods.FindAsync(food.Id))!; savedFood.Name = "Renamed Latte"; savedFood.Price = 50000; await db.SaveChangesAsync(); Clear();
 var details = Json(await controller.Detail(id)); Check(details.GetProperty("Items")[0].GetProperty("FoodName").GetString() == "Latte" && details.GetProperty("Items")[0].GetProperty("Price").GetDecimal() == 35000, "Historical name and price remain frozen");
 var list = Json(await controller.List(type: "Takeaway", status: 1, search: "HD" + id.ToString("D6")));
 Check(list.GetProperty("total").GetInt32() == 1 && list.GetProperty("revenue").GetDecimal() == 63000, "Order filters and totals match paid takeaway");
 Check(await controller.List(from: DateTime.Today.AddDays(1), to: DateTime.Today) is BadRequestObjectResult, "Invalid date range rejected");
 var from = Json(await controller.List(from: DateTime.Today, to: DateTime.Today.AddDays(1))); Check(from.GetProperty("total").GetInt32() == 1, "Day filter includes today");
 await Reject(() => invoices.Refund(id, new() { Reason = "" }, "tester"), "Refund requires reason");
 // Another guest occupies the old table: refunding the earlier bill must not release it.
 var dine = await flow.Add(new() { IdTable = table.Id, IdFood = food.Id, Count = 1 }); await flow.Send(dine); Clear();
 await invoices.Refund(id, new() { Reason = "Demo refund", PaymentMethod = "Transfer" }, "tester"); Clear();
 var refunded = (await db.Bills.FindAsync(id))!;
 Check(refunded.Status == 3 && refunded.RefundAmount == 63000 && refunded.CancelledBy == "tester", "Refund stores amount reason actor and timestamp");
 Check(await db.CashEntries.CountAsync(c => c.IdBill == id) == 2 && await db.CashEntries.Where(c => c.IdBill == id && c.Direction == "Out").SumAsync(c => c.Amount) == 63000, "Refund preserves receipt and creates separate cash out");
 Check((await db.Ingredients.FindAsync(milk.Id))!.Quantity == 970 && await db.BillInfos.Where(i => i.IdBill == id).SumAsync(i => i.Count) == 2, "Paid cancellation preserves consumed stock and historical items");
 Check((await db.TableFoods.FindAsync(table.Id))!.Status == "Có người", "Refund does not clear another active table");
 await invoices.Refund(id, new() { Reason = "Retry", PaymentMethod = "Cash" }, "tester"); Clear();
 Check(await db.CashEntries.CountAsync(c => c.IdBill == id) == 2, "Refund retry cannot pay twice");
 Check(Json(await controller.List()).GetProperty("revenue").GetDecimal() == 0 && Json(await controller.List()).GetProperty("refunded").GetDecimal() == 63000, "Refunded invoice excluded from revenue");
 Check(Json(await kitchen.Pending()).EnumerateArray().All(o => o.GetProperty("IdBill").GetInt32() != id), "Refunded order absent from kitchen");
 Check(await kitchen.Status(kitchenId, new() { Status = "Cooking" }) is BadRequestObjectResult, "Refunded kitchen ticket cannot reopen"); Clear();
 await Reject(() => invoices.Refund(dine, new() { Reason = "Not paid" }, "tester"), "Serving invoice cannot use paid refund");
 var empty = await invoices.Takeaway(new() { RequestKey = Guid.NewGuid().ToString() }, "tester");
 Check(await checkout.CloseEmpty(empty) is OkResult, "Empty takeaway closes without table"); Clear();
 Check(await db.CashEntries.CountAsync(c => c.IdBill == empty) == 0, "Empty close creates no cash entry");
 var dineBill = (await db.Bills.FindAsync(dine))!; var tableEntity = (await db.TableFoods.FindAsync(table.Id))!; tableEntity.Name = "Renamed table"; await db.SaveChangesAsync();
 await checkout.Checkout(dine, new() { PaymentMethod = "Cash" }); Clear();
 var after = (await db.TableFoods.FindAsync(table.Id))!; after.Name = "New name again"; await db.SaveChangesAsync(); Clear();
 Check(Json(await controller.Detail(dine)).GetProperty("TableName").GetString() == "Renamed table", "Paid table label remains frozen after rename");
 Check(Json(await controller.List(status: 3)).GetProperty("total").GetInt32() == 1, "Refund status filter works");
 var legacy = new Bill { IdTable = table.Id, Status = 1, TotalPrice = 40000, PaymentMethod = "Unknown", DateCheckOut = DateTime.Now };
 db.Bills.Add(legacy); await db.SaveChangesAsync(); await invoices.Refund(legacy.Id, new() { Reason = "Legacy refund" }, "tester"); Clear();
 Check(await db.CashEntries.Where(c => c.IdBill == legacy.Id && c.Direction == "In").SumAsync(c => c.Amount) == 40000, "Legacy refund preserves original receipt in cashbook");
 Check(await db.CashEntries.Where(c => c.IdBill == legacy.Id && c.Direction == "Out").SumAsync(c => c.Amount) == 40000, "Legacy refund offsets income exactly");
 var dashboard = Json(await new DashboardController(db).GetOverview());
 Check(dashboard.GetProperty("Summary").GetProperty("TodayRevenue").GetDecimal() == 50000, "Dashboard offsets refunds on their refund date");
 var oldUnknown = new Bill { IdTable = table.Id, Status = 1, DateCheckOut = DateTime.Now, BillInfos = [new() { Food = (await db.Foods.FindAsync(food.Id))!, Count = 1 }] };
 db.Bills.Add(oldUnknown); await db.SaveChangesAsync();
 await Reject(() => invoices.Refund(oldUnknown.Id, new() { Reason = "Unknown actual amount" }, "tester"), "Estimated old receipt cannot trigger an invented refund amount");
 Check(Json(await controller.Detail(oldUnknown.Id)).GetProperty("Estimated").GetBoolean(), "Historical amount missing is clearly marked estimated");
 Check(Json(await controller.List()).GetProperty("estimated").GetInt32() == 1, "List reports number of estimated legacy invoices");
 var cash = Json(await new CashbookController(db).Get(DateTime.Today, DateTime.Today));
 Check(cash.GetProperty("TotalIn").GetDecimal() - cash.GetProperty("TotalOut").GetDecimal() == 50000 && cash.GetProperty("LegacyAmount").GetDecimal() == 50000, "Recorded cash excludes unrecorded legacy income and offsets refunds");
 Console.WriteLine($"All {checks} order checks passed.");
} finally { await db.Database.EnsureDeletedAsync(); }
